### PR TITLE
Replace flask branch with beta and fix it's dir structure

### PR DESCRIPTION
**Pull request by HepoH3**
Also I've reverted `host_network:true` because of #18, and fixed mac placeholders.
Note, that in the repository.json I've add 'fork' suffix to distinguish repositories on the addons page.
#21, #15

### CODE REVIEW

**Comment by HepoH3** [comment]
I checked this addon and all working fine.

**Comment by FeikoJoosten** [comment]
@HepoH3 I tried out your branch, but I cannot seem to generate the `config.json` file required for custom settings. Neither can I connect to Deconz. (Most likely due to the config file not being found)

**Comment by HepoH3** [comment]
> 
> 
> @HepoH3 I tried out your branch, but I cannot seem to generate the `config.json` file required for custom settings. Neither can I connect to Deconz. (Most likely due to the config file not being found)

See: https://github.com/MaxBec/hassio-diyHue/issues/21#issuecomment-871637006. I can't tell why config.json is not creating while install, I used this integration only to simulate hue bridge and use it outside of home assistant or any other hubs like deconz and control lights via hue sync on PC for the music lights (which still works pretty bad but I think it's either yeelight bulbs or hue sync software problems). The goal of this PR is to fix install issues of diyhue-beta branch that related to the changes in dir structure of the repository. The config.json problem seems to be related to some other changes that I don't know how to fix.

**Comment by FeikoJoosten** [comment]
The only thing I can think of is the addition of the `host_network` parameter added to `config.json` (in the root). Apart from that, it _should_ still generate the config file based on what I can see in the code from the diyhue dev branch. (as long as there are no permission issues for some reason). I'd have to fork your repro and see if this actually is the issue. But I'll have to come back on you for that.

**Comment by HepoH3** [comment]
> 
> 
> The only thing I can think of is the addition of the `host_network` parameter added to `config.json` (in the root). Apart from that, it _should_ still generate the config file based on what I can see in the code from the diyhue dev branch. (as long as there are no permission issues for some reason). I'd have to fork your repro and see if this actually is the issue. But I'll have to come back on you for that.

If that the case, I'll revert my commit that return host_network back, but I faced problems with yeelight bulbs discovering without that parameter.

**Comment by FeikoJoosten** [comment]
If that is actually the issue, then I'd say it's a bug. But that should then be relayed to the diyhue devs. But let's first see if that's the actual issue or not 😛.

**Comment by FeikoJoosten** [comment]
Okay, so after a shitload of trial and error I've come to the realization that it is something on the diyhue teams side. Even on a fresh install inside of Docker. It won't create a config file. However, it does create one when using the master branch. Which brings me to the assumption where I believe this is a bug on their end.

**Comment by genehand** [comment]
Hey looks like the config path moved: https://github.com/diyhue/diyHue/issues/646#issuecomment-879193822

I symlinked `/opt/hue-emulator/config` to `/config/diyhue` to get it working, then found it's a new yaml based config and not the original `config.json`.  The settings screen is empty for me and I don't see any docs on all that yet so I'll hold off :)

**Comment by MaxBec** [comment]
hey guys,

i will fix a lot of bugs here soon. had a bit of family trouble in the last months but now everything is fine again.

**Review by MaxBec — APPROVED** [review]

**Pull request merged**
